parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  project: tsconfig.json
  sourceType: 'module'
plugins:
  - '@typescript-eslint/eslint-plugin'
  - functional
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:prettier/recommended'
root: true
env:
  node: true
  jest: true
rules:
  '@typescript-eslint/consistent-type-imports': error
  'functional/immutable-data': error
  'functional/no-let': error
